#!/bin/bash

FILENAME=$1
shift

echo $FILENAME
echo ${FILENAME%%.cpp}

g++ $FILENAME $@ -o ${FILENAME%%.cpp} -L/home/pi/rpi-rgb-led-matrix/lib -lrgbmatrix -lrt -lm -lpthread -I/home/pi/rpi-rgb-led-matrix/include
